Разбивка компонента «Конструктор пиццы» на мелкие компоненты
htmlacademy-vue/397653-pizza-1 pull request #2
Opened 2022-04-04 15:38 UTC by ZhukovaVarvara

---
:mortar_board: [Разбивка компонента «Конструктор пиццы» на мелкие компоненты](https://up.htmlacademy.ru/vue/1/user/397653/tasks/3)

2022-04-05 00:23 UTC, enotke requested changes

2022-04-05 00:23 UTC, enotke commented on src/frontend/src/common/components/ItemCounter.vue
> +      minValue: MIN_INGREDIENT_VALUE,
Если хочешь использовать константы в темплейле, то лучше добавлять их в $options или возвращать в computed свойствах.

2022-04-05 00:23 UTC, enotke commented on src/frontend/src/common/components/RadioButton.vue
> +    classNames: {
classNames тут не нужен. Лучше написать вот так 
`<RadioButton class="dough__input ....." />`

2022-04-05 00:23 UTC, enotke commented on src/frontend/src/common/components/RadioButton.vue
> +      @change="$emit('getValue', value, name, item.multiplier)"
`getValue` странное название события. Событие - это какое-то действие. Лучше назвать change или как-то так

2022-04-05 00:23 UTC, enotke commented on src/frontend/src/common/components/RadioButton.vue
> +    item: {
Из объекта item используется только multiplier, лучше его и передавать

2022-04-05 00:23 UTC, enotke commented on src/frontend/src/common/constants.js
> +export const DOUGH_PRICE = 300;
`Так как цена теста и соуса не изменяется, я вынесла эту стоимость в константы, нормальная ли это практика? (файл common/constants.js)`

Да, если у тебя есть какие-то постоянные значения, то их нужно выносить в константы. Сейчас это выглядит логично.

2022-04-05 00:23 UTC, enotke commented on src/frontend/src/common/constants.js
> +export const DOUGH_PRICE = 300;
Но смысл в том, что стоимость теста и соуса должна приходить из API и в следующих заданиях это будет реализовано. Так что нужно будет не забыть переделать

2022-04-05 00:23 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> +      value = mapDough[value]
Есть же метод getDoughValue

2022-04-05 00:23 UTC, enotke commented on src/frontend/src/views/Index.vue
> +      ingredientPrice: 0,
Итоговую цену нужно делать в виде вычисляемого значения. Тогда не придется каждый раз его изменять

2022-04-05 00:23 UTC, enotke commented on src/frontend/src/views/Index.vue
> +    getValue(value, name, multiplier) {
Лучше разбить это на разные методы. setDough, setSauce

2022-04-05 00:23 UTC, enotke commented on src/frontend/src/common/helpers.js
> +  let index = getIndex(ingredient, ingredients)
Как-то очень запутанно. Ты хранишь количество в ingredients и в pizzaIngredients.

2022-04-05 00:23 UTC, enotke commented on src/frontend/src/common/helpers.js
> +  let index = getIndex(ingredient, ingredients)
И всё это для того, чтобы поменять классы в BuilderPizzaView? Не проще ли передавать туда ingredients? Там же тоже есть количество

2022-04-05 00:23 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> +export default {
Нужно добавить названия для всех компонентов

2022-04-05 00:23 UTC, enotke commented on src/frontend/src/views/Index.vue
> +        this.multiplier = multiplier
Ну и multiplier лучше получать исходя из размера пиццы, а не обновлять его постоянно

2022-04-05 00:23 UTC, enotke commented on src/frontend/src/common/helpers.js
> +  ingredients[index].count = ingredient.count + 1;
Ну и ты везде меняешь объекты которые передаются по ссылке в функцию. Тоже не самый лучший вариант

2022-04-05 00:25 UTC, enotke commented
` В компоненте Index есть компонент BuilderIngredientsSelector, в котором есть компонент ItemCounter. Из ItemCounter я передаю данные в BuilderIngredientsSelector, а из BuilderIngredientsSelector в Index, нормальная ли эта практика? На сколько я поняла, сразу из ItemCounter не получится передать значения в Index`

В целом это нормально. Есть разные способы как этого избежать. Можно использовать глобальный стор, шину событий, provide/inject.

2022-04-05 00:26 UTC, enotke commented
Если остались какие-то вопросы можешь писать в телеграм id: `@Enotke`

2022-04-06 07:53 UTC, ZhukovaVarvara commented
@enotke, спасибо большое! Со всем разобралась, внесла изменения.
Что можно было не трогать, пока что не трогала 🙂

2022-04-07 01:43 UTC, enotke requested changes

2022-04-07 01:43 UTC, enotke commented on src/frontend/src/App.vue
> +import IndexHome from '@/views/Index';
Название компонента должно соответствовать названию файла

2022-04-07 01:43 UTC, enotke commented on src/frontend/src/common/components/ItemCounter.vue
> +    ingredient: {
Старайся не передавать в пропсы объекты. Не совсем понятно что в этом объекте должно быть и что используется компонентом. Тут можно передавать только count. В добавок его можно будет валидировать

2022-04-07 01:43 UTC, enotke commented on src/frontend/src/views/Index.vue
> +    setDought(value) {
Опечатка

2022-04-07 01:43 UTC, enotke commented on src/frontend/src/views/Index.vue
> +      this.multiplier = value
Нужно хранить размер пиццы, а не множитель. Как ты потом будешь добавлять пиццу в корзину?

2022-04-07 01:43 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +      return (number) => {
А зачем делать свойство которое возвращает функцию? Не проще ли сделать метод getIngredientClasses?

2022-04-07 01:43 UTC, enotke commented on src/frontend/src/views/Index.vue
> +          :sauces="this.sauces"
Не нужно использовать this в темплейте

2022-04-07 01:43 UTC, enotke commented on src/frontend/src/views/Index.vue
> +      this.pizzaSauceClass = value
Тут же по идее хранится sauceValue, а не class. И с dough так же

2022-04-10 19:12 UTC, merged