HTTP. Работа с сервером
htmlacademy-vue/397653-pizza-1 pull request #5
Opened 2023-01-09 16:25 UTC by ZhukovaVarvara

---
:mortar_board: [HTTP. Работа с сервером](https://up.htmlacademy.ru/vue/1/user/397653/tasks/6)

2023-01-10 06:59 UTC, enotke commented on src/frontend/src/store/modules/Builder.js
> +      pizza.dough = pizza.dough.map((item) => normalizeDough(item));
Можно просто передавать функцию `pizza.dough.map(normalizeDough)`

2023-01-10 06:59 UTC, enotke commented on src/frontend/src/store/modules/Builder.js
> +          item.count = 0;
item передается по ссылке. Из за этого count меняется в state.pizzaConstructor и state.pizza

2023-01-10 06:59 UTC, enotke commented on src/frontend/src/store/modules/Cart.js
> +      state.additionals.map((item) => (item.count = 0));
Array.map должен возвращать новый элемент массива

2023-01-10 11:45 UTC, ZhukovaVarvara commented on src/frontend/src/store/modules/Cart.js
> +      state.additionals.map((item) => (item.count = 0));
@enotke здесь тогда лучше использовать forEach?

2023-01-10 12:26 UTC, enotke commented on src/frontend/src/store/modules/Cart.js
> +      state.additionals.map((item) => (item.count = 0));
Да, можно

2023-01-10 12:49 UTC, ZhukovaVarvara commented on src/frontend/src/store/modules/Builder.js
> +          item.count = 0;
@enotke корректно ли использовать такую конструкцию:
```
state.pizzaConstructor.ingredients = cloneDeep(state.pizza.ingredients).map(
        (item) => {
          item.count = 0;
          return item;
        }
      );
```

2023-01-10 16:01 UTC, enotke commented on src/frontend/src/store/modules/Builder.js
> +          item.count = 0;
Так то можно, но зачем?
Можно просто возвращать новый элемент массива
`        item => ({
          ...item,
          count: 0;
          })`

2023-01-11 04:51 UTC, ZhukovaVarvara commented on src/frontend/src/store/modules/Builder.js
> +          item.count = 0;
поняла, спасибо!

2023-02-26 12:04 UTC, S-le reviewed
Просмотрев работу, написал точечные комментарии.

1. Ошибка `TypeError: Cannot read properties of undefined (reading 'getToken')` возникла из-за того, что файл с плагинами не был импортирован в **main.js**.

2. Не реализована работа с нотификациями.

3. Разобраться со страницами `layout`. Постарался расписать в комментариях.

4. Доделать страницу `/orders`.

Работы ещё много, но у тебя есть время разобраться. Могу отметить, что страница авторизации сделана хорошо. Реализована валидация, работа с формой и отправка запроса на сервер.

Во многих компонентах есть проблема со связыванием данных. В компоненте описано свойство `props`, но данные не передаются в него из родительского компонента. Такие места необходимо переработать и по возможности использовать возможности Vuex.

Я рекомендовал бы тебе ещё раз проработать модуль 4. Работа с нотификацией описана в нём ([4.17. Компонент нотификаций](https://up.htmlacademy.ru/vue/1/module/4/item/17)).

Если всё-таки возникают вопросы или есть непонимание раздела, лучше заказать консультацию. Куратор может помочь тебе, разобрав твой код. 

Не забывай перепроверять соответствие проекта технической документации.

Ты проделала большую работу. Разделы 4 и 5, на мой взгляд, самые сложные. Но разобраться в них нужно досконально. Описанные в них приёмы это основная часть работы с Vue2. Так что, старательно изучай материал и всё обязательно получится. 

Если мои комментарии оставили вопросы, то можешь написать мне.
Просмотрев работу, написал точечные комментарии.

1. Ошибка `TypeError: Cannot read properties of undefined (reading 'getToken')` возникла из-за того, что файл с плагинами не был импортирован в **main.js**.

2. Не реализована работа с нотификациями.

3. Разобраться со страницами `layout`. Постарался расписать в комментариях.

4. Доделать страницу `/orders`.

Работы ещё много, но у тебя есть время разобраться. Могу отметить, что страница авторизации сделана хорошо. Реализована валидация, работа с формой и отправка запроса на сервер.

Во многих компонентах есть проблема со связыванием данных. В компоненте описано свойство `props`, но данные не передаются в него из родительского компонента. Такие места необходимо переработать и по возможности использовать возможности Vuex.

Я рекомендовал бы тебе ещё раз проработать модуль 4. Работа с нотификацией описана в нём ([4.17. Компонент нотификаций](https://up.htmlacademy.ru/vue/1/module/4/item/17)).

Если всё-таки возникают вопросы или есть непонимание раздела, лучше заказать консультацию. Куратор может помочь тебе, разобрав твой код. 

Не забывай перепроверять соответствие проекта технической документации.

Ты проделала большую работу. Разделы 4 и 5, на мой взгляд, самые сложные. Но разобраться в них нужно досконально. Описанные в них приёмы это основная часть работы с Vue2. Так что, старательно изучай материал и всё обязательно получится. 

Если мои комментарии оставили вопросы, то можешь написать мне.

2023-02-26 12:04 UTC, S-le commented on src/frontend/src/main.js
>  import router from './router';
Ошибка *TypeError: Cannot read properties of undefined (reading 'getToken')* возникает в компоненте **App.vue** при попытке вызвать функцию `this.$jwt.getToken()`. `$jwt` это пользовательский плагин. Он был успешно зарегистрирован в коде (`vuePlugins.js`). Вот только файл следовало импортировать `import './plugins/vuePlugins'`. Т.к. система сборки работает таким образом, что подключает только файлы которые находит после ключевого слова **import**. 

Вот такая мелочь может привести к ошибке. Ничего страшного, такое бывает со всеми.

2023-02-26 12:04 UTC, S-le commented on src/frontend/src/common/helpers.js
> +  store.dispatch("Auth/getMe");
Неверное обращение к модулю Vuex. Поскольку модуль зарегистрирован с [собственным пространством имён](https://v3.vuex.vuejs.org/ru/guide/modules.html#%D0%BF%D1%80%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%BD%D1%81%D1%82%D0%B2%D0%B0-%D0%B8%D0%BC%D0%B5%D0%BD) (`namespaced: true`), то обращение к нему производится по имени. Причём имя является регистрозависимым. `store.dispatch("Auth/getMe");` здесь *auth* это пространство имен модуля, а *getMe* сам action который вызывается. Сама библиотека Vuex парсит строку и находит action.

Когда модуль регистрируется, то ему присваивается его пространство имен. В твоём случае это `@/store/index.js` в блоке 
```
modules: {
    auth: Auth,
    ...
}
```
Как можно заметить, здесь пространство имен **auth**, значит и обращаться надо store.dispatch("auth/getMe");`.

2023-02-26 12:04 UTC, S-le commented on src/frontend/src/store/index.js
> +    commit(ADD_NOTIFICATION, uniqueNotification);
Мутация **ADD_NOTIFICATION** не реализована. Эта тема была в модуле [4.10. Мутации (mutations) и экспорт](https://up.htmlacademy.ru/vue/1/module/4/item/10).

2023-02-26 12:04 UTC, S-le commented on src/frontend/src/store/index.js
> +      () => commit(DELETE_NOTIFICATION, uniqueNotification.id),
Мутация **DELETE_NOTIFICATION** не определена. Это тема была в модуле [4.10. Мутации (mutations) и экспорт](https://up.htmlacademy.ru/vue/1/module/4/item/10).)

2023-02-26 12:04 UTC, S-le commented on src/frontend/src/store/index.js
> +const state = () => ({});
В state должен быть определен массив `notifications`. Эта тема из раздела [4.8. Корневой модуль store и состояния](https://up.htmlacademy.ru/vue/1/module/4/item/8).

2023-02-26 12:04 UTC, S-le commented on src/frontend/src/layouts/AppLayout.vue
>        const layout = this.$route.meta.layout || defaultLayout;
Рекомендую перечитать модуль [3.8. Добавление автоматических шаблонов в проект](https://up.htmlacademy.ru/vue/1/module/3/item/8). Там достаточно понятный пример как сделать несколько шаблонов. В этом проекте можно сделать похоже. 

Всё же в двух словах опишу проблему. Т.к. по задумке пользоваться сайтом "VUE Pizza" могут авторизованные и не авторизованные пользователи. То у авторизованного пользователя появляются дополнительные страницы, а соответственно дополнительные пункты меню.

Из примера видно, что компонент `AppLayoutDefault.vue` это шаблон, который рендерится по умолчанию. У нас даже есть запись `const defaultLayout = 'AppLayoutDefault';`. Такой шаблон должен отображаться на всех страницах.

Однако в примере есть компонент `AppLayoutMain.vue`. Это тоже шаблон, но он уже не является шаблоном по умолчанию. И будет использоваться в специально указанных местах. В твоем случае это `this.$route.meta.layout`.

Но ещё есть `AppLayoutHeader.vue`, этот компонент содержит часть шаблона, которую можно переиспользовать в `AppLayoutDefault.vue` и `AppLayoutMain.vue`.

2023-02-26 12:04 UTC, S-le commented on src/frontend/src/router/index.js
> +const routes = [
Массив `routes` лучше вынести в отдельный файл **routes.js**. Таким образом в этом файле останется только настройка роутера. А все роуты будут лежать отдельно. Ведь со временем в реальном проекте количество роутов может значительно увеличиться.

2023-02-26 12:04 UTC, S-le commented on src/frontend/src/middlewares/isAdmin.js
> +  if (!store.state.Auth.user?.isAdmin) {
Тут желательно разобраться, что происходит в коде. Поскольку эта проверка всегда будет возвращать **false**.
1. Модуля *Auth* не существует. В `@/store/index.js` он был зарегистрирован как *auth*. В этом можно убедиться посмотрев в раздел "Vuex" в Vue Devtools. Регистр в названии модуля очень важно. Фактически store это объект у которого есть поле auth.
2. `isAdmin` такого поля не существует. Собственно, в проекте, в отличие от примера, пользователь не может быть админом. В тестовом проекте проверяется авторизован ли он. Поэтому данный middleware не нужен.

2023-02-26 12:04 UTC, S-le commented on src/frontend/src/middlewares/auth.js
> +  if (!store.state.Auth.isAuthenticated) {
Перепроверь название модуля. Подробно описал проблему комментарием к файлу `isAdmin.js`.

2023-02-26 12:04 UTC, S-le commented on src/frontend/src/common/helpers.js
> +export const mapIngredientName = {
Такие объекты (`mapIngredientName, mapSauceName, mapDough, mapSizes`) стоит выносить в **enum**.

2023-02-26 12:04 UTC, S-le commented on src/frontend/src/common/helpers.js
>    "45 см": "big"
Конечно, спецификация не запрещает использовать в качестве имен свойств объекта числа, кирилические символы, выражения и даже эмодзи. Однако, по возможности лучше этого избегать. Это не ошибка, а просто рекомендация.

2023-02-26 12:04 UTC, S-le commented on src/frontend/src/views/Index.vue
>    name: 'Index',
Имена компонентов должны всегда состоять из нескольких слов. Исключение компонент **App.vue**. Это связано с тем, что в HTML имя элемента это всегда одно слов. В спецификацию HTML добавляются новые элементы и может возникнуть путаница. [Вот ссылка на рекомендации из документации](https://ru.vuejs.org/v2/style-guide/#%D0%98%D0%BC%D0%B5%D0%BD%D0%B0-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%BE%D0%B2-%D0%B8%D0%B7-%D0%BD%D0%B5%D1%81%D0%BA%D0%BE%D0%BB%D1%8C%D0%BA%D0%B8%D1%85-%D1%81%D0%BB%D0%BE%D0%B2-%D0%B2%D0%B0%D0%B6%D0%BD%D0%BE).

Например, этот компонет может иметь имя `BuilderPage`.

2023-02-26 12:04 UTC, S-le commented on src/frontend/src/views/Index.vue
> +    ...mapActions("builder", ["getSaucesData"]),
В таком случае достаточно одной строки, а не трех. В mapActions вторым параметром в массиве перечислить `["getIngredientsData", "getDoughData", "getSaucesData"]`.

2023-02-26 12:04 UTC, S-le commented on src/frontend/src/views/Index.vue
> +          <BuilderDoughSelector/>
В компоненте `BuilderDoughSelector.vue` определ обязательный входной параметр **dough**. Но он не передается в компонент. Больше комментов в `BuilderDoughSelector.vue`.

2023-02-26 12:04 UTC, S-le commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> +          @changePizza="$emit('changePizza', dough)"
`dough` передается входным параметром в компонент. Однако, из компонента Index.vue нечего не передается, поэтому переменная `dough === undefined`. Из-за этого в строке `v-for="dough in dough"` возникает ошибка, т.к. undefined не массив. 
Используй Vuex. Получи из стора список dough. 

Для изменение теста используется пользовательское событие (emit) `changePizza`. В `Index.vue` такое событие не обрабатывается. Соответственно, не может измениться. Здесь тоже используй Vuex. И отправляй *action* в этом компоненте. 

Так можно разорвать такую тесную связь с компонентом Index.vue.

2023-02-26 12:04 UTC, S-le commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +            @changePizza="$emit('changePizza', sauce)"
Здесь такая же проблема как в `BuilderDoughSelector.vue`.

2023-02-26 12:04 UTC, S-le commented on src/frontend/src/modules/builder/components/BuilderSizeSelector.vue
> +          @changePizza="$emit('changePizza', size)"
Здесь такая же проблема как в BuilderDoughSelector.vue.

2023-02-26 12:04 UTC, S-le commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
>        pizzaName: ''
Теперь, когда работа происходит с Vuex, то не стоит определять `pizzaName` в *data*. Поскольку работа происходит со стором, то следует брать это значение из него.

2023-02-26 12:04 UTC, S-le commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +    setName(val) {
Рекомендую почитать этот раздел [документации vuex](https://v3.vuex.vuejs.org/ru/guide/forms.html#%D0%B4%D0%B2%D1%83%D0%BD%D0%B0%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%BD%D1%8B%D0%B5-%D0%B2%D1%8B%D1%87%D0%B8%D1%81%D0%BB%D1%8F%D0%B5%D0%BC%D1%8B%D0%B5-%D1%81%D0%B2%D0%BE%D0%B8%D1%81%D1%82%D0%B2%D0%B0). В нём написано как легко определить в компоненте `pizzaName` из стора, чтобы в секции *template* воспользоваться `v-model`.

2023-02-26 12:04 UTC, S-le commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
>        <BuilderPriceCounter :totalPrice="totalPrice"/>
`totalPrice`, как и другие свойства компоненте определённые в опции *props* должные передаваться в компонент из родительского компонента (в твоём случае `Index.vue`).

Лучше воспользоваться Vuex и получить эти данные их стора.

2023-02-26 12:04 UTC, S-le commented on src/frontend/src/common/components/AppInput.vue
> +  },
Эта конструкция используется по умолчанию для `v-model` на компоненте ([Документация](https://ru.vuejs.org/v2/guide/components.html#%D0%98%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-v-model-%D0%BD%D0%B0-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0%D1%85)). Если ты используешь свои имена, то её можно и не прописывать в коде.

2023-02-26 12:04 UTC, S-le commented on src/frontend/src/common/mixins/logout.js
> +      await this.$store.dispatch("Auth/logout");
Проверь имя модуля!

2023-02-26 12:04 UTC, S-le commented on src/frontend/src/views/Index.vue
> +          <BuilderSizeSelector/>
Не передаются входные данные!

2023-02-26 12:04 UTC, S-le commented on src/frontend/src/views/Index.vue
> +          <BuilderIngredientsSelector/>
Не передаются входные данные!

2023-02-26 12:04 UTC, S-le commented on src/frontend/src/views/Index.vue
> +    dropIngredients(drop) {
Этот метод не используется в компоненте.

2023-02-26 12:04 UTC, S-le commented on src/frontend/src/views/Login.vue
> +      await this.$router.push("/");
Это кончено тестовый проект. Но в реальном проекте желательно дождаться ответа от сервера и только после делать редирект. Сервер может вернуть ошибку.

2023-02-26 12:04 UTC, S-le commented on src/frontend/src/store/modules/auth.js
> +          { module: 'Auth', entity: 'isAuthenticated', value: true },
Проверяй имя модуля!

2023-02-26 12:04 UTC, S-le commented on src/frontend/src/store/modules/auth.js
> +          { module: 'Auth', entity: 'user', value: data },
Проверяй имя модуля!

2023-02-26 12:04 UTC, S-le commented on src/frontend/src/layouts/AppLayoutHeader.vue
>          <span>Выйти</span>
Не написано действие на кнопку "Выйти". Невозможно разлогиниться.

2023-02-26 12:04 UTC, S-le commented on src/frontend/src/modules/cart/components/CartFooter.vue
> +      </button>
Из [технического задания](https://up.htmlacademy.ru/vue/1/project/pizza#specification) **3.3.4 Оформление заказа**:
> Если авторизованный пользователь нажимает на кнопку «Оформить заказ», то показывается попап «Спасибо за заказ», данные о заказе передаются на backend...

Куда добавить эту логику решать тебе. Но в `Cart.vue` этого тоже нет.

2023-02-26 12:04 UTC, S-le commented on src/frontend/src/modules/cart/components/CartAdditional.vue
> +    additionals: {
`additionals` можно получить из стора сразу в компоненте.

2023-02-26 12:04 UTC, S-le commented on src/frontend/src/views/Index.vue
> +    this.getMiscData();
Не хватает загрузки размеров пиццы. `/sizes`

2023-02-26 12:04 UTC, S-le commented on src/frontend/src/views/Cart.vue
> +    ...mapGetters("cart", ["getPizzas", "getTotalPrice"]),
Геттер `getPizzas` не определён, скорее всего имелся ввиду `getPizza`. Будь внимательней.

2023-02-26 12:04 UTC, S-le commented on src/frontend/src/views/Cart.vue
> +    ...mapState("cart", ["additionals", "delivery"]),
В модуле card нет *additionals* и *delivery*.

2023-02-26 12:04 UTC, S-le commented on src/frontend/src/modules/orders/OrdersPizzaItem.vue
> +      return names.map((el) => el.toLowerCase()).join(", ");
`.toLowerCase()` можно сделать в конструкции *map* выше и не перебирать массив ещё раз.

2023-03-02 09:35 UTC, ZhukovaVarvara commented on src/frontend/src/modules/orders/OrdersPizzaItem.vue
> +      return names.map((el) => el.toLowerCase()).join(", ");
@S-le спасибо огромное за тщательную проверку! Потихоньку разбираюсь и всё становится намного понятнее)

2023-03-15 03:25 UTC, S-le reviewed
Ты хорошо поработала, я понимаю, что это самая сложная тема. Но это самая важная тема. Работа практически готова к сдаче, осталось её доработать.

Замечания я оставил комментариями к коду. Там же можно найти рекомендации. 

Внимательно перечитай техническое задание. Проект после этой темы должен полностью ему соответствовать. 

Не следует усложнять реализацию. Я посмотрел на работу с Vuex. Не стоит так делать обновление state в модулях. По крайней мере в учебном проекте. 

Просмотри замечания и постарайся всё проработать. Если после этого будут вопросы или ты, что-то не поймешь, то рекомендую взять голосовую консультацию. Эффект от неё должен быть больше.

Успехов в учёбе!

2023-03-15 03:25 UTC, S-le commented on src/frontend/src/common/components/AppInput.vue
> +    },
Входной параметр `type` используется для определения типа элемена *input*. Это не плохое решение, но у элмента `<input />` есть много значений атрибута `type`(например *checkbox*, *file*, *button* и [т.д.](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#input_types)). В таком случае лучше добавить [валидацию входного параметра](https://ru.vuejs.org/v2/guide/components-props.html#%D0%92%D0%B0%D0%BB%D0%B8%D0%B4%D0%B0%D1%86%D0%B8%D1%8F-%D0%B2%D1%85%D0%BE%D0%B4%D0%BD%D1%8B%D1%85-%D0%BF%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%D0%BE%D0%B2), что для учебного проекта будет достаточно. 
Ещё вариант сделать функциональные компоненты-обёртки над компонентом `AppInput.vue` для каждого разрешенного случая.

2023-03-15 03:25 UTC, S-le commented on src/frontend/src/common/components/AppNotifications.vue
> +  color: $white-900;
`$white-900` это SCSS переменная. Она должна быть определена в проекте. Например, ниже в файле используется переменная `$orange-300` и она определена в `/home/leos/repos/397653-pizza-1/src/frontend/src/assets/scss/ds-system/ds-colors.scss`. Добавь определения для переменных в этот файл или используй сразу цвета в css правилах. Перепроверь все SCSS переменные в файле.

2023-03-15 03:25 UTC, S-le commented on src/frontend/src/plugins/ui.js
> +Vue.component("AppNotifications", AppNotifications);
Компонент `AppNotifications` зарегистрирован глобально. Но я не нашёл места где он используется в коде. Соответственно после возникновения ошибки *notification* не отображается.

2023-03-15 03:25 UTC, S-le commented on src/frontend/src/plugins/ui.js
> +Vue.component("AppLayout", AppLayout);
После глобальной регистрации компонента он будет доступен внутри каждого компонента. Кроме того их не нужно будет импортировать этот компонент. Такая регистрация имеет месть быть для компонентов которые будут использоваться во всем проекте. Есть много компромиссов, лучше сделаю отсылку к [документации](https://ru.vuejs.org/v2/guide/components-registration.html#%D0%93%D0%BB%D0%BE%D0%B1%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D1%80%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D1%8F);
Компонент `AppLayout` используется в приложении один раз. На мой взгляд его можно импортировать и зарегистрировать локально. Компонент `AppInput`лучше подходит для глобальной регистрации.

2023-03-15 03:25 UTC, S-le commented on src/frontend/src/common/mixins/validator.js
> +﻿/* eslint-disable */
Линтер отключать не стоит🙀.

2023-03-15 03:25 UTC, S-le commented on src/frontend/src/common/mixins/validator.js
> +      value ? emailRegex.test(String(value).toLowerCase()) : true,
Чтобы не использовать метод `toLowerCase` в регулярное выражение можно добавить [флаг `i`](https://learn.javascript.ru/regexp-introduction#flagi).

2023-03-15 03:25 UTC, S-le commented on src/frontend/src/layouts/AppLayoutHeader.vue
> +              alt="Василий Ложкин"
А сервера возвращается "Вася Пупкин".

2023-03-15 03:25 UTC, S-le commented on src/frontend/src/layouts/AppLayoutHeader.vue
> +    },
Оба вычисляемые свойства зависят от переменной `user`. Однако, когда пользователь не авторизован, то `user` присвоено значение **null**. Следует добавить проверки на *null*. А ещё лучше вынести эти вычисляемые свойства, вместе со специфичным для авторизованного пользователя кодом (`v-if="user"`), из этого компонента в отдельный. И использовать его в конструкции `v-if="user"`. Тогда в этом новом компоненте не надо делать проверки, что `user !== null` поскольку компонент будет загружен только когда `user !== null`.

2023-03-15 03:25 UTC, S-le commented on src/frontend/src/store/modules/builder.js
> +    },
На примере этого геттера хочу обратить внимание на семантику. Свойство `label` это как раз название на русском. Его я ожидаю увидеть в интерфейсе. Даже если [обратиться к HTML](https://developer.mozilla.org/ru/docs/Web/HTML/Element/label), то увидим:
> **HTML-элемент <label> **представляет собой подпись к элементу пользовательского интерфейса.

А вот свойство `name` может иметь значение *"small"*.

Это просто рекомендация, ошибки этом нет.

2023-03-15 03:25 UTC, S-le commented on src/frontend/src/store/modules/builder.js
> +    },
На примере этого геттера покажу ошибку.
Vuex это библиотека в основе которой лежит паттерн "Состояние". А значит состояние (state) может быть изменено только предсказуемым образом через mutations. Getter можно считать вычисляемыми свойствами хранилища.
Так вот, ошибка в том, что внутри геттера происходит изменение state.
Лучше использовать `return state.sauces.map(...)` и создавать новые объекты с новыми свойствами.

2023-03-15 03:25 UTC, S-le commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +    },
Можно отказаться от этого метода и сразу использовать в шаблоне `setCurrentSauce`.

2023-03-15 03:25 UTC, S-le commented on src/frontend/src/store/modules/auth.js
> +      );
А зачем так усложнять? Ты и так внутри модуля `auth`. Проще написать мутацию и вызвать её. Это и понятнее будет и тестировать легче.

2023-03-15 03:25 UTC, S-le commented on src/frontend/src/views/Profile.vue
> +              alt="Василий Ложкин"
Используй `user.name` или что-то абстрактное, например *изображение пользователя*.

2023-03-15 03:25 UTC, S-le commented on src/frontend/src/modules/profile/ProfileAddressForm.vue
> +          type="submit"
`type="button"` в этом случае.

2023-03-15 03:25 UTC, S-le commented on src/frontend/src/store/modules/addresses.js
> +      );
`await this.$api.addresses.delete(id)` возвращает только Promise<void>. Затем ты вызываешь эту конструкцию, которая фактически нечего не делает. 
Тут два варианта как можно изменить:
1) Мы доверяем клиенту и послу получения ответа от сервера удаляем этот адрес из стора.
2) Мы вызываем action `getAddresses` и получаем свежий список адресов.

2023-03-15 03:25 UTC, S-le commented on src/frontend/src/modules/profile/ProfileAddressForm.vue
> +      $event.target.submit();
Так не пойдет. В проекте для работы с сервером не используем нативный submit.

2023-03-15 03:25 UTC, S-le commented on src/frontend/src/store/modules/addresses.js
> +    },
В этих функциях, как и в `deleteAddress` необходимо доработать. После добавления/изменения адреса просто перезапроси список адресов.

2023-03-15 03:25 UTC, S-le commented on src/frontend/src/modules/profile/ProfileAddressForm.vue
> +  name: "ProfileAddressForm",
Добавить валидацию полей. В этом компоненте можно использовать `AppInput.vue`.

2023-03-15 03:25 UTC, S-le commented on src/frontend/src/common/helpers.js
> +};
В рамках это проекта можно было сделать проще. Ведь тебе не нужная такая низкая вероятность повторения. Можно было использовать **timestamp**. Ещё в проек подключен *lodash*, а там есть такая функция как [uniqueId](https://lodash.com/docs/4.17.15#uniqueId). Это не ошибка, просто совет, что не надо излишне усложнять.

2023-03-15 03:25 UTC, S-le commented on src/frontend/src/views/Cart.vue
> +  name: "Cart",
Из технического задания [п 3.3](https://up.htmlacademy.ru/vue/1/project/pizza):
> Корзина доступна всем пользователям. Если в корзине нет ни одного товара, то отображается div.cart__empty. Если в корзине есть товары — отображаются все основные блоки

А у тебя сейчас есть надпись "В корзине нет ни одного товара", но при этом можно купить "Острый соус" и оформить заказ. Это надо поправить.

2023-03-15 03:25 UTC, S-le commented on src/frontend/src/views/Cart.vue
> +                <ItemCounter
Ограничение на максимальное количество пицц быть не должно.

2023-03-15 03:25 UTC, S-le commented on src/frontend/src/views/Cart.vue
> +      this.setTotalPrice(pricePizza + this.getPriceMisc);
Расчёт стоимости дополнительных товаров `getPriceMisc` происходит в геттере. Я бы в геттер также добавил расчёт стоимости пицц и итоговую стоимость. Тогда не надо долать эти расчёты при добавлении пиццы или изменении доп. товаров. Итоговая стоимость будет сама реактивно пересчитываться. И в header будешь её спокойно использовать.

2023-03-15 03:25 UTC, S-le commented on src/frontend/src/modules/cart/components/CartModal.vue
> +      } else this.$router.push({ name: "IndexHome" });
Следи за форматированием кода.

2023-03-15 03:25 UTC, S-le commented on src/frontend/src/modules/cart/components/CartForm.vue
> +    changeAddress(value) {
Их технического задания [3.3.3 Данные о доставке](https://up.htmlacademy.ru/vue/1/project/pizza):
> Изменять параметры существующего адреса на странице корзины нельзя.

2023-03-15 03:25 UTC, S-le commented on src/frontend/src/modules/orders/OrdersPizzaItem.vue
> +    },
Метод возвращает массив который вставляется в template. Можно применить `names.join()`, чтобы возвращать сразу строку.

2023-03-15 03:25 UTC, S-le commented on src/frontend/src/modules/orders/OrdersItem.vue
> +          <button type="submit" class="button button--border">Удалить</button>
`type="button"`

2023-03-15 03:25 UTC, S-le commented on src/frontend/src/modules/orders/OrdersItem.vue
> +        <button @click="repeatOrder()" class="button">Повторить</button>
`type="button"`

2023-03-15 03:25 UTC, S-le commented on src/frontend/src/modules/orders/OrdersItem.vue
> +      return this.order.orderPizzas.map((pizza) => {
У объекта `this.order` нет свойства `orderPizzas`. Вычисляемое свойство возвращает ошибку.

2023-03-15 03:25 UTC, S-le commented on src/frontend/src/modules/orders/OrdersItem.vue
> +      return this.getOrderPrice(this.pizzas, this.order.orderMisc);
`this.pizzas` возвращает ошибку и соответственно `orderPrice` тоже.

2023-03-17 10:07 UTC, S-le commented on src/frontend/src/views/Login.vue
> +      await this.$router.push("/");
Попробуй залогиниться введя неверный пароль. Оберни этот код в try/catch.

2023-03-17 12:02 UTC, S-le requested changes
Ты молодец! Ты проделала большую работу. Проект уже на финишной прямой и скоро будет закончен. После этого модуля должны быть выполнены все пункты тех. задания. Поэтому давай доделаем последние ошибочки.

1. На странице `/cart` не хватает ограничения минимального количества. Смотри подробности в комментариях к коду. Сейчас можно заказать -1 пиццу.
2. `/history`. Не работает кнопка "Удалить". Подробности в комментариях к кнопке.
3. `/history`. После нажатия на кнопку "Повторить" невозможно оформить заказ. Есть проблема с ингредиентами. Подробности в комментариях к коду.
4. `/profile`. Не корректно работает кнопка "Изменить" адрес. Она не должна перезагружать страницу.
5. `/profile`. После создания нового адреса скрывать форму "Новый адрес".

Список небольшой и ошибки не страшные. Исправь и внимательно перепроверь соответствие проекта тех. заданию.

На этот модуль потрачено много времени, но повторюсь он очень важен. Следующая тема будет проще.

2023-03-17 12:02 UTC, S-le commented on src/frontend/src/common/components/ItemCounter.vue
>      }
Молодец! Ещё одно решение перенести старые вычисляемые свойства в `props`:
```    
minValue() {
    return MIN_INGREDIENT_VALUE
},
maxValue() {
    return MAX_INGREDIENT_VALUE
}
```
Для `minValue` сделать `default: MIN_INGREDIENT_VALUE`. Для `maxValue` сделать `default: Infinity`.

2023-03-17 12:02 UTC, S-le commented on src/frontend/src/store/modules/cart.js
> +    },
Достаточно в компоненте сразу получать данные из state `state.pizza`. Т.к. фактически такие геттеры бесполезны. Если сравнить его с `getPricePizzas`, то там происходит вычисление стоимости. Это значение кэшируется и при каждом обращении его не надо вычислять заного.

2023-03-17 12:02 UTC, S-le commented on src/frontend/src/store/modules/builder.js
> +    labeledlSauces(state) {
Опечатка.

2023-03-17 12:02 UTC, S-le commented on src/frontend/src/layouts/AppLayoutHeader.vue
> +    },
Про эту ошибку писал! Не стоит это игнорировать.

2023-03-17 12:02 UTC, S-le commented on src/frontend/src/views/Cart.vue
> +                  />
Не хватает ограничения на минимальное количество. И в списке с пиццами тоже.

2023-03-17 12:02 UTC, S-le commented on src/frontend/src/views/Cart.vue
> +              <div class="counter cart-list__counter">
Из пункта [3.3.1 ТЗ](https://up.htmlacademy.ru/vue/1/project/pizza#specification):
>Можно добавить ещё пиццу за счёт нажатия + или убрать одну за счет нажатия -. При изменении количества пицц меняется сумма в пункте товара, а также меняется итоговая сумма в корзине. Если количество товара равно нулю, то товар удаляется из корзины.

2023-03-17 12:02 UTC, S-le commented on src/frontend/src/modules/orders/OrdersItem.vue
> +      </form>
Тут не отправляется форма на удаление. Достаточно добавить событие к элементу `button @click="deleteOrder(order.id)"`.

2023-03-17 12:02 UTC, S-le commented on src/frontend/src/modules/orders/OrdersPizzaItem.vue
> +      return names.join()
У метода строки [join есть параметр](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/join) почитай. Сейчас строка выглядит `ветчина,чили`.

2023-03-17 12:02 UTC, S-le commented on src/frontend/src/modules/orders/OrdersItem.vue
> +        <button type="button" @click="repeatOrder()" class="button">Повторить</button>
Кнопка "Повторить" работает с ошибкой. Все данные заказа добавляются в корзину, происходит переход на страницу корзины. Вот только оформить заказ не получается. С сервера возвращается ошибка. Проверь массив `state.cart.pizza.ingredients` там есть проблема. Иногда в объекте массива есть свойство `count`, а иногда `quantity`. Из-за этого на сервер не отправляется информация о количестве ингредиентов.

2023-03-17 12:02 UTC, S-le commented on src/frontend/src/views/Cart.vue
> +                </button>
Рекомендую тебе почитать про HTML елемент `<form>`. Как он работает и как оправляет данные на сервер. Про `submit`. В этом месте вся страница после `click` перезагружается. Самый быстрый вариант как этого измежать добить модификатор `prevent` к событию `click.prevent=...`. Вот про [модификатор](https://ru.vuejs.org/v2/guide/events.html#%D0%9C%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80%D1%8B-%D1%81%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D0%B9), а это тоже [почитай](https://learn.javascript.ru/default-browser-action).

2023-03-24 15:19 UTC, S-le reviewed
Отлично проделанная работа! Ты все исправила и доделала работу. Приятно видеть, что ты смогла разобраться в теме.

Отвечаю на вопросы:
1.  > Если пользователь авторизован при оформлении заказа, при нажатии на кнопку "Отлично, я жду" должно перебрасывать на страницу заказов, но иногда возникает ошибка в консоли 
```Error in v-on handler (Promise/async): "Error: Navigation cancelled from "/cart" to "/orders" with a new navigation."```

Оставил ответ комментарием в `CartModal.vue`.

2. > При перебрасывании на страницу истории заказов из корзины возникает ошибка
Error in render: "TypeError: Cannot read properties of undefined (reading 'price')"
Тоже не могу разобраться из-за чего именно она появляется.

После того как пользователь закрывает модальное окно, вызывается метод:
```
async closeModal() {
    this.resetCartState()

    if (this.user !== null) {
        await this.$router.push({ name: "Orders" });
    } else {
        await this.$router.push({ name: "IndexHome" });
    }
}
```

`resetCartState` присваивает значению `misc` из Vuex модуля `card` значение `[]`. (`misc = []`)

На следующем шаге происходит перенаправление нв страницу `/orders` (`await this.$router.push({ name: "Orders" });`).

Открывается страница `/orders`. В хуке `created` вызывается метод `await this.getMiscData()` (запрашивает с сервера список *misc*). А пока данные с сервера возвращаются строиться список компонентов `<OrdersItem />`.

Каждый компонент `OrdersItem.vue` вычисляет `orderPrice`. И вот здесь и происходит ошибка. 
``` 
const miscPrices = misc.map(
    (misc) => getItemById(this.misc, misc.miscId).price * misc.quantity
);
```
Поскольку данные с сервера все еще в пути, то this.misc пустой массив. А это значит, что `getItemById(this.misc, misc.miscId)` возвращает `undefined` и которого свойства `price` быть не может.

Надеюсь это поможет тебе в исправлении.


Также хочу обратить твое внимание на то, что изменения в state вносятся только в мутациях. Я заметил несколько геттеров в которых изменяется state. Это необходимо исправить.

Помимо этого оставил небольшие рекомендации в комментариях. 

Доделывай домашнее задание и отправляй на проверку. Буду ждать.

2023-03-24 15:19 UTC, S-le commented on src/frontend/src/common/components/ItemCounter.vue
> +      required: false,
Свойство `required` по умолчанию *false*, следовательно можно не писать эту строку.

2023-03-24 15:19 UTC, S-le commented on src/frontend/src/common/components/ItemCounter.vue
> +    minValue: {
Если посудить, то количество ингридиентов это всегда натуральное число, включая ноль. Следовательно, можно сделать из `minValue` вычисляемое свойство.

2023-03-24 15:19 UTC, S-le commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
>                  :transfer-data="ingredient"
В этом месте ты используешь стиль именования *kebab-case* (`:transfer-data`), а чуть ниже *camelCase* (`:maxValue`). Приведи все к одному стилю.

2023-03-24 15:19 UTC, S-le commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
>      }
Нигде не используется.

2023-03-24 15:19 UTC, S-le commented on src/frontend/src/store/modules/cart.js
> +      var sumPriceMisc = 0;
Используй не `var`, a `let` для объявления переменной.

2023-03-24 15:19 UTC, S-le commented on src/frontend/src/store/modules/cart.js
> +      return state.misc;
В геттере нельзя изменять **state**! Если ты хочешь вернить новый массив с измененными объектами, то внутри `map` создавай новый объект.

2023-03-24 15:19 UTC, S-le commented on src/frontend/src/modules/cart/components/CartModal.vue
> +      <a href="#" class="button" @click="closeModal()"> Отлично, я жду! </a>
Ошибка возникает из-за того, то элемент `<a href="#"></a>` это ссылка. При клике на неё происходит переход по ссылке. Но токже срабатывает событие *click* которые запускает работу *vue-router*. В следствии этого происходит конфликт. Чтобы исправить это отменить действие браузера по умолчанию. `@click.prevent=""` [вот ссылка на документацию](https://ru.vuejs.org/v2/guide/events.html#%D0%9C%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80%D1%8B-%D1%81%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D0%B9).

2023-03-29 10:56 UTC, S-le requested changes
Великолепно! Могу тебя только похвалить. Ты большая умница. Прекрасно наблюдать в тебе такое качество как упорность. 

Больше мне добавить нечего. Переходи к следующей теме. С ней ты легко справишься.

2023-03-29 10:56 UTC, S-le commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +    },
Метод `setPizzaName` не делает нечего. Можно сразу вызывать `setCurrentPizzaName`.

2023-03-29 10:56 UTC, merged

2023-04-03 09:46 UTC, S-le requested changes
Отличная работа, продолжай в том же духе!